# Dependencies
# markdown:         redcarpet
# highlighter:      pygments


# Setup
title:    John Laudun
tagline:  'Mapping Stories across Networks of People'
description: 'People «» Stories «» Networks'
version:  "2022-12-27"
url:      https://johnlaudun.net/
baseurl:  https://johnlaudun.net/

author:
  name:           'John Laudun'
  url:            https://zirk.us/johnlaudun

plugins: [jekyll-paginate]
paginate:         10

github: 
  repo:           https://github.com/johnlaudun/blog/
