# Dependencies
# markdown:         redcarpet
# highlighter:      pygments


# Setup
title: John Laudun
# tagline:          'Mapping Stories across Networks'
description: 'People «» Stories «» Networks'
version:  "2022-12-27"
url: https://johnlaudun.github.io/blog/
baseurl: https://johnlaudun.github.io/blog/

author:
  name:           'John Laudun'
  url:            https://zirk.us/johnlaudun

plugins: [jekyll-paginate]
paginate:         5

github: 
  repo:           https://github.com/johnlaudun/blog/
